## Perez Llera Leonardo
## 6BM1
## Red multicapa
##

In [20]:
import numpy as np

In [21]:
def sigmoid(x):
    return 1  /(1 + np.exp(-x))

In [22]:
nInput = 4
nHidden = 3
nOut = 2

In [23]:
mean = 0.0
stdev = 0.1

np.random.seed(42)
weightsInput = np.random.normal(mean, scale=stdev, size=(nInput, nHidden))
weightsHidden = np.random.normal(mean, scale=stdev, size=(nHidden, nOut))

x = np.random.randn(4)

print(weightsInput)
print(weightsHidden)
print(x)

[[ 0.04967142 -0.01382643  0.06476885]
 [ 0.15230299 -0.02341534 -0.0234137 ]
 [ 0.15792128  0.07674347 -0.04694744]
 [ 0.054256   -0.04634177 -0.04657298]]
[[ 0.02419623 -0.19132802]
 [-0.17249178 -0.05622875]
 [-0.10128311  0.03142473]]
[-0.90802408 -1.4123037   1.46564877 -0.2257763 ]


In [25]:
h = np.dot(x, weightsInput)
out = sigmoid(h)

print("Input layer:")
print(out)

h = np.dot(out, weightsHidden)
out = sigmoid(h)

print("Output layer:")
print(out)

Input layer:
[0.48975306 0.54204203 0.4790029 ]
Output layer:
[0.46750523 0.47274472]
